### ISSUE TITLE
error retrieving the update (present since 10 days or so)

### ISSUE THREAD

**Issue by avichou** [sannidhyaroy/Soduto#20]
<img width="276" alt="image" src="https://github.com/sannidhyaroy/Soduto/assets/86660671/ea16dbfa-4d67-401f-800a-0dc65dd8512f">

**Comment by sannidhyaroy** [comment]
I'm sorry for the bad experience but the site that served the app update information was on a `.tk` domain that expired very recently, since I forgot to renew it. I had the domain was many years and I initially got it when I was a middle-school student and obviously I couldn't afford to pay for a domain back then.

I have changed the code and pointed it to the new site (although I haven't pushed it to GitHub) and update functionalities should work fine after you manually update one last time from the next release.

**Comment by avichou** [comment]
> I'm sorry for the bad experience but the site that served the app update information was on a `.tk` domain that expired very recently, since I forgot to renew it. I had the domain for many years and I initially got it when I was a middle-school student and obviously I couldn't afford to pay for a domain back then.
> 
> I have changed the code and pointed it to the new site (although I haven't pushed it to GitHub) and update functionalities should work fine after you manually update one last time from the next release.
> 
> Sorry for the trouble!

hey, no need to be sorry! thanks for supporting and improving this beautiful app, thanks for your work 

one last time from the next release...meaning i gotta wait for the next 2.0.3 release to be able to update in-app instread of checking on github , right? reinstalling 2.0.2 from scratch rn will make no difference, right?

**Comment by sannidhyaroy** [comment]
> one last time from the next release...meaning i gotta wait for the next 2.0.3 release to be able to update in-app instread of checking on github , right? reinstalling 2.0.2 from scratch rn will make no difference, right?

Yes, that is right! I need to update all instances of the expired domain with the new domain in Soduto's `info.plist` file as well as update the `appcast.xml` in the site that stores all information related to updates to the app.

I'm wondering if I should create a new release (v2.0.3) or just update the `.dmg` file in the v2.0.2 release for this small hotfix.

**Comment by sannidhyaroy** [comment]
This should be fixed after updating to the latest release manually from GitHub!
Can anyone check?

**Comment by avichou** [comment]
> > one last time from the next release...meaning i gotta wait for the next 2.0.3 release to be able to update in-app instread of checking on github , right? reinstalling 2.0.2 from scratch rn will make no difference, right?
> 
> Yes, that is right! I need to update all instances of the expired domain with the new domain in Soduto's `info.plist` file as well as update the `appcast.xml` in the site that stores all information related to updates to the app.
> 
> I'm wondering if I should create a new release (v2.0.3) or just update the `.dmg` file in the v2.0.2 release for this small hotfix.

couldnt answer before sorry. yeah you did what I would have advised, too , by releasing a 0.3 update for it 

think it'd be a good idea to mention the fact that updates will work ONLY on the latest 2.0.3 version (put that in 0.3 description)

**Comment by avichou** [comment]
> This should be fixed after updating to the latest release manually from GitHub! Can anyone check? If it's not working for someone, first please ensure that [soduto.thenoton.com](https://soduto.thenoton.com) is accessible from your device and your firewall or ISP isn’t blocking it for some reason.

works for me !
