### ISSUE TITLE
Launch on login not working/inconsistent

### ISSUE THREAD

**Issue by emdoe** [sannidhyaroy/Soduto#8]
Hi, thanks again for the great job!

> first you might take a look in System Preferences if you have enabled the toggle of Soduto under Login Items, just to be sure there's nothing wrong in your part.

I enabled it and then tried to deactivate and re-enable it.  But unfortunately, nothing changed.

> Also, just a quick question: Do you get that sign when you clone my repo and build it yourself in Xcode or you have the issue even when you downloaded the dmg from my latest release?

I directly download and installed it from the `.dmg`. Because I had previously installed agungrbudiman's version, I attempted to remove all files and reinstall your version. But still nothing had changed.

(related to https://github.com/agungrbudiman/Soduto/issues/9#issuecomment-1402391527).

**Comment by sannidhyaroy** [comment]
> I directly download and installed it from the `.dmg`. Because I had previously installed agungrbudiman's version, I attempted to remove all files and reinstall your version. But still nothing had changed.

Thanks for the update! Will try to fix it in the next version, if possible.

**Comment by sannidhyaroy** [comment]
This issue has been improved in f5196da10b35a7eb980daeaccf73b2befadb8fe3.
